<template>
    <a-card :title="t('TTSCONFIG_CardTitle')" id="tts-config-card">
        <template #extra>
            <i v-if="cardIsOpen" class="fa-sharp fa-minus text-white"></i>
            <i v-else class="fa-sharp fa-plus text-white"></i>
        </template>
        <div class="flex flex-col gap-1">
            <!-- TTS Service Selection -->
            <div class="form-section">
                <p class="form-label">{{ t('TTSCONFIG_FormLabelSelectTTSService') }}</p>
                <a-select v-model="ttsConfigStore.config.service" :allow-search="true" @change="()=>{ttsConfigStore.updateConfig({voice:''})}">
                    <a-option key="edge" value="edge">
                      {{ t('TTSCONFIG_OptionEdge') }}
                    </a-option>
                    <a-option key="azure" value="azure">
                      {{ t('TTSCONFIG_OptionAzure') }}
                    </a-option>
                </a-select>
            </div>

            <!-- Azure Region + Key (Only if azure selected) -->
            <div v-if="ttsConfigStore.config.service === 'azure'">
                <div class="form-section mt-2">
                    <p class="form-label">{{ t('TTSCONFIG_FormLabelAzureRegion') }}</p>
                    <a-select v-model="ttsConfigStore.config.azureRegion" :allow-search="true" @change="saveConfig">
                    <a-option v-for="region in azureRegions" :key="region.Name" :value="region.Name">
                        {{ region.DisplayName }}
                    </a-option>
                </a-select>
                </div>
                <div class="form-section mt-2">
                    <p class="form-label">{{ t('TTSCONFIG_FormLabelAzureKey') }}</p>
                    <a-input-password v-model="ttsConfigStore.config.azureKey" @change="saveConfig" />
                </div>
            </div>

            <!-- Voice selection -->
            <div id="voice" class="mt-3">
                <p class="form-label">{{ t('TTSCONFIG_FormLabelVoice') }}</p>
                <a-select v-model="ttsConfigStore.config.voice" :allow-search="true" @change="saveConfig">
                    <a-option v-for="voice in voiceList" :key="voice" :value="voice">
                        {{ voice }}
                    </a-option>
                </a-select>
            </div>
            <div id="form-pitch" class="mt-3">
                <p class="form-label">{{ t('TTSCONFIG_FormLabelPitch') }}</p>
                <a-slider class="grow pl-0.5" :min="-50" :max="50" show-input :show-tooltip="false"
                    v-model="ttsConfigStore.config.pitch" @change="saveConfig" />
            </div>
            <div id="form-speed">
                <p class="form-label">{{ t('TTSCONFIG_FormLabelSpeed') }}</p>
                <a-slider class="grow pl-0.5" :min="-50" :max="50" show-input :show-tooltip="false"
                    v-model="ttsConfigStore.config.speed" @change="saveConfig" />
            </div>
            <div id="form-words-per-section">
                <p class="form-label">{{ t('TTSCONFIG_FormLabelWordsPerSection') }}</p>
                <a-slider class="grow pl-0.5" :min="100" :max="500" show-input :show-tooltip="false"
                    v-model="ttsConfigStore.config.wordsPerSection" @change="saveConfig" />
            </div>
            <div id="form-job-concurrency">
                <p class="form-label">{{ t('TTSCONFIG_FormLabelConcurrentJobs') }}</p>
                <a-slider class="grow pl-0.5" :min="1" :max="20" show-input :show-tooltip="false"
                    v-model="ttsConfigStore.config.jobConcurrencyLimit" @change="saveConfig" />
            </div>
            <div id="form-section-concurrency">
                <p class="form-label">{{ t('TTSCONFIG_FormLabelConcurrentSections') }}</p>
                <a-slider class="grow pl-0.5" :min="1" :max="20" show-input :show-tooltip="false"
                    v-model="ttsConfigStore.config.sectionConcurrencyLimit" @change="saveConfig" />
            </div>
            <div id="form-output-format">
                <p class="form-label">{{ t('TTSCONFIG_OutputFormat') }}</p>
                <a-select v-model="ttsConfigStore.config.outputFormat" default-value="m4b" @change="saveConfig">
                    <a-option v-for="format in formats">{{ format }}</a-option>
                </a-select>
            </div>
        </div>
    </a-card>
</template>

<script setup lang="ts">
import { ref, nextTick, onMounted, computed } from 'vue';
import { useTTSConfigStore } from '../store';
import { useI18n } from 'vue-i18n';

const { t } = useI18n();
const ttsConfigStore = useTTSConfigStore();

const cardIsOpen = ref(true)
const toggleCardOpen = () => {
    cardIsOpen.value = !cardIsOpen.value
}

// On mount, ensure we have the config loaded
onMounted(async () => {
    await ttsConfigStore.loadConfigFromMain();
    setupCardCollapse();
});

function setupCardCollapse() {
    nextTick(() => {
        const cardHeader = document.querySelector("#tts-config-card .arco-card-header") as HTMLElement;
        const cardBody = document.querySelector("#tts-config-card .arco-card-body") as HTMLElement;
        if (!cardHeader || !cardBody) return;
        cardHeader.addEventListener('click', () => {
            toggleCardOpen();
            cardBody.classList.toggle("hidden");
        });
        cardHeader.classList.add("cursor-pointer");
    });
}

const voiceList = computed(() => {
    // If user chooses edge => load a list of voices for Edge
    // If user chooses azure => load a different list
    // For now, you can filter or do an IPC call:
    return ttsConfigStore.config?.service === 'azure' ? azureVoices : edgeVoices;
});

const formats = [
    "m4b",
    "mp3",
    "m4a"
]

async function saveConfig() {
    await ttsConfigStore.saveConfigToMain();
}

const azureVoices = [
    "af-ZA-AdriNeural",
    "af-ZA-WillemNeural",
    "am-ET-MekdesNeural",
    "am-ET-AmehaNeural",
    "ar-AE-FatimaNeural",
    "ar-AE-HamdanNeural",
    "ar-BH-LailaNeural",
    "ar-BH-AliNeural",
    "ar-DZ-AminaNeural",
    "ar-DZ-IsmaelNeural",
    "ar-EG-SalmaNeural",
    "ar-EG-ShakirNeural",
    "ar-IQ-RanaNeural",
    "ar-IQ-BasselNeural",
    "ar-JO-SanaNeural",
    "ar-JO-TaimNeural",
    "ar-KW-NouraNeural",
    "ar-KW-FahedNeural",
    "ar-LB-LaylaNeural",
    "ar-LB-RamiNeural",
    "ar-LY-ImanNeural",
    "ar-LY-OmarNeural",
    "ar-MA-MounaNeural",
    "ar-MA-JamalNeural",
    "ar-OM-AyshaNeural",
    "ar-OM-AbdullahNeural",
    "ar-QA-AmalNeural",
    "ar-QA-MoazNeural",
    "ar-SA-ZariyahNeural",
    "ar-SA-HamedNeural",
    "ar-SY-AmanyNeural",
    "ar-SY-LaithNeural",
    "ar-TN-ReemNeural",
    "ar-TN-HediNeural",
    "ar-YE-MaryamNeural",
    "ar-YE-SalehNeural",
    "as-IN-YashicaNeural",
    "as-IN-PriyomNeural",
    "az-AZ-BanuNeural",
    "az-AZ-BabekNeural",
    "bg-BG-KalinaNeural",
    "bg-BG-BorislavNeural",
    "bn-BD-NabanitaNeural",
    "bn-BD-PradeepNeural",
    "bn-IN-TanishaaNeural",
    "bn-IN-BashkarNeural",
    "bs-BA-VesnaNeural",
    "bs-BA-GoranNeural",
    "ca-ES-JoanaNeural",
    "ca-ES-EnricNeural",
    "ca-ES-AlbaNeural",
    "cs-CZ-VlastaNeural",
    "cs-CZ-AntoninNeural",
    "cy-GB-NiaNeural",
    "cy-GB-AledNeural",
    "da-DK-ChristelNeural",
    "da-DK-JeppeNeural",
    "de-AT-IngridNeural",
    "de-AT-JonasNeural",
    "de-CH-LeniNeural",
    "de-CH-JanNeural",
    "de-DE-KatjaNeural",
    "de-DE-ConradNeural",
    "de-DE-SeraphinaMultilingualNeural",
    "de-DE-FlorianMultilingualNeural",
    "de-DE-AmalaNeural",
    "de-DE-BerndNeural",
    "de-DE-ChristophNeural",
    "de-DE-ElkeNeural",
    "de-DE-GiselaNeural",
    "de-DE-KasperNeural",
    "de-DE-KillianNeural",
    "de-DE-KlarissaNeural",
    "de-DE-KlausNeural",
    "de-DE-LouisaNeural",
    "de-DE-MajaNeural",
    "de-DE-RalfNeural",
    "de-DE-TanjaNeural",
    "de-DE-Seraphina:DragonHDLatestNeural",
    "el-GR-AthinaNeural",
    "el-GR-NestorasNeural",
    "en-AU-NatashaNeural",
    "en-AU-WilliamNeural",
    "en-AU-AnnetteNeural",
    "en-AU-CarlyNeural",
    "en-AU-DarrenNeural",
    "en-AU-DuncanNeural",
    "en-AU-ElsieNeural",
    "en-AU-FreyaNeural",
    "en-AU-JoanneNeural",
    "en-AU-KenNeural",
    "en-AU-KimNeural",
    "en-AU-NeilNeural",
    "en-AU-TimNeural",
    "en-AU-TinaNeural",
    "en-CA-ClaraNeural",
    "en-CA-LiamNeural",
    "en-GB-SoniaNeural",
    "en-GB-RyanNeural",
    "en-GB-LibbyNeural",
    "en-GB-AdaMultilingualNeural",
    "en-GB-OllieMultilingualNeural",
    "en-GB-AbbiNeural",
    "en-GB-AlfieNeural",
    "en-GB-BellaNeural",
    "en-GB-ElliotNeural",
    "en-GB-EthanNeural",
    "en-GB-HollieNeural",
    "en-GB-MaisieNeural",
    "en-GB-NoahNeural",
    "en-GB-OliverNeural",
    "en-GB-OliviaNeural",
    "en-GB-ThomasNeural",
    "en-GB-MiaNeural",
    "en-HK-YanNeural",
    "en-HK-SamNeural",
    "en-IE-EmilyNeural",
    "en-IE-ConnorNeural",
    "en-IN-AaravNeural",
    "en-IN-AashiNeural",
    "en-IN-AnanyaNeural",
    "en-IN-KavyaNeural",
    "en-IN-KunalNeural",
    "en-IN-NeerjaNeural",
    "en-IN-PrabhatNeural",
    "en-IN-RehaanNeural",
    "en-IN-AartiNeural",
    "en-IN-ArjunNeural",
    "en-KE-AsiliaNeural",
    "en-KE-ChilembaNeural",
    "en-NG-EzinneNeural",
    "en-NG-AbeoNeural",
    "en-NZ-MollyNeural",
    "en-NZ-MitchellNeural",
    "en-PH-RosaNeural",
    "en-PH-JamesNeural",
    "en-SG-LunaNeural",
    "en-SG-WayneNeural",
    "en-TZ-ImaniNeural",
    "en-TZ-ElimuNeural",
    "en-US-AvaMultilingualNeural",
    "en-US-AndrewMultilingualNeural",
    "en-US-EmmaMultilingualNeural",
    "en-US-BrianMultilingualNeural",
    "en-US-AvaNeural",
    "en-US-AndrewNeural",
    "en-US-EmmaNeural",
    "en-US-BrianNeural",
    "en-US-JennyNeural",
    "en-US-GuyNeural",
    "en-US-AriaNeural",
    "en-US-DavisNeural",
    "en-US-JaneNeural",
    "en-US-JasonNeural",
    "en-US-KaiNeural",
    "en-US-LunaNeural",
    "en-US-SaraNeural",
    "en-US-TonyNeural",
    "en-US-NancyNeural",
    "en-US-CoraMultilingualNeural",
    "en-US-ChristopherMultilingualNeural",
    "en-US-BrandonMultilingualNeural",
    "en-US-AmberNeural",
    "en-US-AnaNeural",
    "en-US-AshleyNeural",
    "en-US-BrandonNeural",
    "en-US-ChristopherNeural",
    "en-US-CoraNeural",
    "en-US-ElizabethNeural",
    "en-US-EricNeural",
    "en-US-JacobNeural",
    "en-US-JennyMultilingualNeural",
    "en-US-MichelleNeural",
    "en-US-MonicaNeural",
    "en-US-RogerNeural",
    "en-US-RyanMultilingualNeural",
    "en-US-SteffanNeural",
    "en-US-AdamMultilingualNeural",
    "en-US-AIGenerate1Neural",
    "en-US-AIGenerate2Neural",
    "en-US-AlloyTurboMultilingualNeural",
    "en-US-AmandaMultilingualNeural",
    "en-US-BlueNeural",
    "en-US-DavisMultilingualNeural",
    "en-US-DerekMultilingualNeural",
    "en-US-DustinMultilingualNeural",
    "en-US-EchoTurboMultilingualNeural",
    "en-US-EvelynMultilingualNeural",
    "en-US-FableTurboMultilingualNeural",
    "en-US-LewisMultilingualNeural",
    "en-US-LolaMultilingualNeural",
    "en-US-NancyMultilingualNeural",
    "en-US-NovaTurboMultilingualNeural",
    "en-US-OnyxTurboMultilingualNeural",
    "en-US-PhoebeMultilingualNeural",
    "en-US-SamuelMultilingualNeural",
    "en-US-SerenaMultilingualNeural",
    "en-US-ShimmerTurboMultilingualNeural",
    "en-US-SteffanMultilingualNeural",
    "en-US-Andrew:DragonHDLatestNeural",
    "en-US-Andrew2:DragonHDLatestNeural",
    "en-US-Aria:DragonHDLatestNeural",
    "en-US-Ava:DragonHDLatestNeural",
    "en-US-Brian:DragonHDLatestNeural",
    "en-US-Davis:DragonHDLatestNeural",
    "en-US-Emma:DragonHDLatestNeural",
    "en-US-Emma2:DragonHDLatestNeural",
    "en-US-Jenny:DragonHDLatestNeural",
    "en-US-Steffan:DragonHDLatestNeural",
    "en-ZA-LeahNeural",
    "en-ZA-LukeNeural",
    "es-AR-ElenaNeural",
    "es-AR-TomasNeural",
    "es-BO-SofiaNeural",
    "es-BO-MarceloNeural",
    "es-CL-CatalinaNeural",
    "es-CL-LorenzoNeural",
    "es-CO-SalomeNeural",
    "es-CO-GonzaloNeural",
    "es-CR-MariaNeural",
    "es-CR-JuanNeural",
    "es-CU-BelkysNeural",
    "es-CU-ManuelNeural",
    "es-DO-RamonaNeural",
    "es-DO-EmilioNeural",
    "es-EC-AndreaNeural",
    "es-EC-LuisNeural",
    "es-ES-ElviraNeural",
    "es-ES-AlvaroNeural",
    "es-ES-ArabellaMultilingualNeural",
    "es-ES-IsidoraMultilingualNeural",
    "es-ES-TristanMultilingualNeural",
    "es-ES-XimenaMultilingualNeural",
    "es-ES-AbrilNeural",
    "es-ES-ArnauNeural",
    "es-ES-DarioNeural",
    "es-ES-EliasNeural",
    "es-ES-EstrellaNeural",
    "es-ES-IreneNeural",
    "es-ES-LaiaNeural",
    "es-ES-LiaNeural",
    "es-ES-NilNeural",
    "es-ES-SaulNeural",
    "es-ES-TeoNeural",
    "es-ES-TrianaNeural",
    "es-ES-VeraNeural",
    "es-ES-XimenaNeural",
    "es-GQ-TeresaNeural",
    "es-GQ-JavierNeural",
    "es-GT-MartaNeural",
    "es-GT-AndresNeural",
    "es-HN-KarlaNeural",
    "es-HN-CarlosNeural",
    "es-MX-DaliaNeural",
    "es-MX-JorgeNeural",
    "es-MX-BeatrizNeural",
    "es-MX-CandelaNeural",
    "es-MX-CarlotaNeural",
    "es-MX-CecilioNeural",
    "es-MX-GerardoNeural",
    "es-MX-LarissaNeural",
    "es-MX-LibertoNeural",
    "es-MX-LucianoNeural",
    "es-MX-MarinaNeural",
    "es-MX-NuriaNeural",
    "es-MX-PelayoNeural",
    "es-MX-RenataNeural",
    "es-MX-YagoNeural",
    "es-NI-YolandaNeural",
    "es-NI-FedericoNeural",
    "es-PA-MargaritaNeural",
    "es-PA-RobertoNeural",
    "es-PE-CamilaNeural",
    "es-PE-AlexNeural",
    "es-PR-KarinaNeural",
    "es-PR-VictorNeural",
    "es-PY-TaniaNeural",
    "es-PY-MarioNeural",
    "es-SV-LorenaNeural",
    "es-SV-RodrigoNeural",
    "es-US-PalomaNeural",
    "es-US-AlonsoNeural",
    "es-UY-ValentinaNeural",
    "es-UY-MateoNeural",
    "es-VE-PaolaNeural",
    "es-VE-SebastianNeural",
    "et-EE-AnuNeural",
    "et-EE-KertNeural",
    "eu-ES-AinhoaNeural",
    "eu-ES-AnderNeural",
    "fa-IR-DilaraNeural",
    "fa-IR-FaridNeural",
    "fi-FI-SelmaNeural",
    "fi-FI-HarriNeural",
    "fi-FI-NooraNeural",
    "fil-PH-BlessicaNeural",
    "fil-PH-AngeloNeural",
    "fr-BE-CharlineNeural",
    "fr-BE-GerardNeural",
    "fr-CA-SylvieNeural",
    "fr-CA-JeanNeural",
    "fr-CA-AntoineNeural",
    "fr-CA-ThierryNeural",
    "fr-CH-ArianeNeural",
    "fr-CH-FabriceNeural",
    "fr-FR-DeniseNeural",
    "fr-FR-HenriNeural",
    "fr-FR-VivienneMultilingualNeural",
    "fr-FR-RemyMultilingualNeural",
    "fr-FR-LucienMultilingualNeural",
    "fr-FR-AlainNeural",
    "fr-FR-BrigitteNeural",
    "fr-FR-CelesteNeural",
    "fr-FR-ClaudeNeural",
    "fr-FR-CoralieNeural",
    "fr-FR-EloiseNeural",
    "fr-FR-JacquelineNeural",
    "fr-FR-JeromeNeural",
    "fr-FR-JosephineNeural",
    "fr-FR-MauriceNeural",
    "fr-FR-YvesNeural",
    "fr-FR-YvetteNeural",
    "ga-IE-OrlaNeural",
    "ga-IE-ColmNeural",
    "gl-ES-SabelaNeural",
    "gl-ES-RoiNeural",
    "gu-IN-DhwaniNeural",
    "gu-IN-NiranjanNeural",
    "he-IL-HilaNeural",
    "he-IL-AvriNeural",
    "hi-IN-AaravNeural",
    "hi-IN-AnanyaNeural",
    "hi-IN-KavyaNeural",
    "hi-IN-KunalNeural",
    "hi-IN-RehaanNeural",
    "hi-IN-SwaraNeural",
    "hi-IN-MadhurNeural",
    "hi-IN-AartiNeural",
    "hi-IN-ArjunNeural",
    "hr-HR-GabrijelaNeural",
    "hr-HR-SreckoNeural",
    "hu-HU-NoemiNeural",
    "hu-HU-TamasNeural",
    "hy-AM-AnahitNeural",
    "hy-AM-HaykNeural",
    "id-ID-GadisNeural",
    "id-ID-ArdiNeural",
    "is-IS-GudrunNeural",
    "is-IS-GunnarNeural",
    "it-IT-ElsaNeural",
    "it-IT-IsabellaNeural",
    "it-IT-DiegoNeural",
    "it-IT-AlessioMultilingualNeural",
    "it-IT-IsabellaMultilingualNeural",
    "it-IT-GiuseppeMultilingualNeural",
    "it-IT-MarcelloMultilingualNeural",
    "it-IT-BenignoNeural",
    "it-IT-CalimeroNeural",
    "it-IT-CataldoNeural",
    "it-IT-FabiolaNeural",
    "it-IT-FiammaNeural",
    "it-IT-GianniNeural",
    "it-IT-GiuseppeNeural",
    "it-IT-ImeldaNeural",
    "it-IT-IrmaNeural",
    "it-IT-LisandroNeural",
    "it-IT-PalmiraNeural",
    "it-IT-PierinaNeural",
    "it-IT-RinaldoNeural",
    "iu-Cans-CA-SiqiniqNeural",
    "iu-Cans-CA-TaqqiqNeural",
    "iu-Latn-CA-SiqiniqNeural",
    "iu-Latn-CA-TaqqiqNeural",
    "ja-JP-NanamiNeural",
    "ja-JP-KeitaNeural",
    "ja-JP-AoiNeural",
    "ja-JP-DaichiNeural",
    "ja-JP-MayuNeural",
    "ja-JP-NaokiNeural",
    "ja-JP-ShioriNeural",
    "ja-JP-MasaruMultilingualNeural",
    "ja-JP-Masaru:DragonHDLatestNeural",
    "jv-ID-SitiNeural",
    "jv-ID-DimasNeural",
    "ka-GE-EkaNeural",
    "ka-GE-GiorgiNeural",
    "kk-KZ-AigulNeural",
    "kk-KZ-DauletNeural",
    "km-KH-SreymomNeural",
    "km-KH-PisethNeural",
    "kn-IN-SapnaNeural",
    "kn-IN-GaganNeural",
    "ko-KR-SunHiNeural",
    "ko-KR-InJoonNeural",
    "ko-KR-HyunsuMultilingualNeural",
    "ko-KR-BongJinNeural",
    "ko-KR-GookMinNeural",
    "ko-KR-HyunsuNeural",
    "ko-KR-JiMinNeural",
    "ko-KR-SeoHyeonNeural",
    "ko-KR-SoonBokNeural",
    "ko-KR-YuJinNeural",
    "lo-LA-KeomanyNeural",
    "lo-LA-ChanthavongNeural",
    "lt-LT-OnaNeural",
    "lt-LT-LeonasNeural",
    "lv-LV-EveritaNeural",
    "lv-LV-NilsNeural",
    "mk-MK-MarijaNeural",
    "mk-MK-AleksandarNeural",
    "ml-IN-SobhanaNeural",
    "ml-IN-MidhunNeural",
    "mn-MN-YesuiNeural",
    "mn-MN-BataaNeural",
    "mr-IN-AarohiNeural",
    "mr-IN-ManoharNeural",
    "ms-MY-YasminNeural",
    "ms-MY-OsmanNeural",
    "mt-MT-GraceNeural",
    "mt-MT-JosephNeural",
    "my-MM-NilarNeural",
    "my-MM-ThihaNeural",
    "nb-NO-PernilleNeural",
    "nb-NO-FinnNeural",
    "nb-NO-IselinNeural",
    "ne-NP-HemkalaNeural",
    "ne-NP-SagarNeural",
    "nl-BE-DenaNeural",
    "nl-BE-ArnaudNeural",
    "nl-NL-FennaNeural",
    "nl-NL-MaartenNeural",
    "nl-NL-ColetteNeural",
    "or-IN-SubhasiniNeural",
    "or-IN-SukantNeural",
    "pa-IN-OjasNeural",
    "pa-IN-VaaniNeural",
    "pl-PL-AgnieszkaNeural",
    "pl-PL-MarekNeural",
    "pl-PL-ZofiaNeural",
    "ps-AF-LatifaNeural",
    "ps-AF-GulNawazNeural",
    "pt-BR-FranciscaNeural",
    "pt-BR-AntonioNeural",
    "pt-BR-MacerioMultilingualNeural",
    "pt-BR-ThalitaMultilingualNeural",
    "pt-BR-BrendaNeural",
    "pt-BR-DonatoNeural",
    "pt-BR-ElzaNeural",
    "pt-BR-FabioNeural",
    "pt-BR-GiovannaNeural",
    "pt-BR-HumbertoNeural",
    "pt-BR-JulioNeural",
    "pt-BR-LeilaNeural",
    "pt-BR-LeticiaNeural",
    "pt-BR-ManuelaNeural",
    "pt-BR-NicolauNeural",
    "pt-BR-ThalitaNeural",
    "pt-BR-ValerioNeural",
    "pt-BR-YaraNeural",
    "pt-PT-RaquelNeural",
    "pt-PT-DuarteNeural",
    "pt-PT-FernandaNeural",
    "ro-RO-AlinaNeural",
    "ro-RO-EmilNeural",
    "ru-RU-SvetlanaNeural",
    "ru-RU-DmitryNeural",
    "ru-RU-DariyaNeural",
    "si-LK-ThiliniNeural",
    "si-LK-SameeraNeural",
    "sk-SK-ViktoriaNeural",
    "sk-SK-LukasNeural",
    "sl-SI-PetraNeural",
    "sl-SI-RokNeural",
    "so-SO-UbaxNeural",
    "so-SO-MuuseNeural",
    "sq-AL-AnilaNeural",
    "sq-AL-IlirNeural",
    "sr-Latn-RS-NicholasNeural",
    "sr-Latn-RS-SophieNeural",
    "sr-RS-SophieNeural",
    "sr-RS-NicholasNeural",
    "su-ID-TutiNeural",
    "su-ID-JajangNeural",
    "sv-SE-SofieNeural",
    "sv-SE-MattiasNeural",
    "sv-SE-HilleviNeural",
    "sw-KE-ZuriNeural",
    "sw-KE-RafikiNeural",
    "sw-TZ-RehemaNeural",
    "sw-TZ-DaudiNeural",
    "ta-IN-PallaviNeural",
    "ta-IN-ValluvarNeural",
    "ta-LK-SaranyaNeural",
    "ta-LK-KumarNeural",
    "ta-MY-KaniNeural",
    "ta-MY-SuryaNeural",
    "ta-SG-VenbaNeural",
    "ta-SG-AnbuNeural",
    "te-IN-ShrutiNeural",
    "te-IN-MohanNeural",
    "th-TH-PremwadeeNeural",
    "th-TH-NiwatNeural",
    "th-TH-AcharaNeural",
    "tr-TR-EmelNeural",
    "tr-TR-AhmetNeural",
    "uk-UA-PolinaNeural",
    "uk-UA-OstapNeural",
    "ur-IN-GulNeural",
    "ur-IN-SalmanNeural",
    "ur-PK-UzmaNeural",
    "ur-PK-AsadNeural",
    "uz-UZ-MadinaNeural",
    "uz-UZ-SardorNeural",
    "vi-VN-HoaiMyNeural",
    "vi-VN-NamMinhNeural",
    "wuu-CN-XiaotongNeural",
    "wuu-CN-YunzheNeural",
    "yue-CN-XiaoMinNeural",
    "yue-CN-YunSongNeural",
    "zh-CN-XiaoxiaoNeural",
    "zh-CN-YunxiNeural",
    "zh-CN-YunjianNeural",
    "zh-CN-XiaoyiNeural",
    "zh-CN-YunyangNeural",
    "zh-CN-XiaochenNeural",
    "zh-CN-XiaochenMultilingualNeural",
    "zh-CN-XiaohanNeural",
    "zh-CN-XiaomengNeural",
    "zh-CN-XiaomoNeural",
    "zh-CN-XiaoqiuNeural",
    "zh-CN-XiaorouNeural",
    "zh-CN-XiaoruiNeural",
    "zh-CN-XiaoshuangNeural",
    "zh-CN-XiaoxiaoDialectsNeural",
    "zh-CN-XiaoxiaoMultilingualNeural",
    "zh-CN-XiaoyanNeural",
    "zh-CN-XiaoyouNeural",
    "zh-CN-XiaoyuMultilingualNeural",
    "zh-CN-XiaozhenNeural",
    "zh-CN-YunfengNeural",
    "zh-CN-YunhaoNeural",
    "zh-CN-YunjieNeural",
    "zh-CN-YunxiaNeural",
    "zh-CN-YunyeNeural",
    "zh-CN-YunyiMultilingualNeural",
    "zh-CN-YunzeNeural",
    "zh-CN-YunfanMultilingualNeural",
    "zh-CN-YunxiaoMultilingualNeural",
    "zh-CN-Xiaochen:DragonHDLatestNeural",
    "zh-CN-guangxi-YunqiNeural",
    "zh-CN-henan-YundengNeural",
    "zh-CN-liaoning-XiaobeiNeural",
    "zh-CN-liaoning-YunbiaoNeural",
    "zh-CN-shaanxi-XiaoniNeural",
    "zh-CN-shandong-YunxiangNeural",
    "zh-CN-sichuan-YunxiNeural",
    "zh-HK-HiuMaanNeural",
    "zh-HK-WanLungNeural",
    "zh-HK-HiuGaaiNeural",
    "zh-TW-HsiaoChenNeural",
    "zh-TW-YunJheNeural",
    "zh-TW-HsiaoYuNeural",
    "zu-ZA-ThandoNeural",
    "zu-ZA-ThembaNeural"
]

const edgeVoices = ["af-ZA-AdriNeural", "af-ZA-WillemNeural", "am-ET-AmehaNeural", "am-ET-MekdesNeural", "ar-AE-FatimaNeural", "ar-AE-HamdanNeural", "ar-BH-AliNeural", "ar-BH-LailaNeural", "ar-DZ-AminaNeural", "ar-DZ-IsmaelNeural", "ar-EG-SalmaNeural", "ar-EG-ShakirNeural", "ar-IQ-BasselNeural", "ar-IQ-RanaNeural", "ar-JO-SanaNeural", "ar-JO-TaimNeural", "ar-KW-FahedNeural", "ar-KW-NouraNeural", "ar-LB-LaylaNeural", "ar-LB-RamiNeural", "ar-LY-ImanNeural", "ar-LY-OmarNeural", "ar-MA-JamalNeural", "ar-MA-MounaNeural", "ar-OM-AbdullahNeural", "ar-OM-AyshaNeural", "ar-QA-AmalNeural", "ar-QA-MoazNeural", "ar-SA-HamedNeural", "ar-SA-ZariyahNeural", "ar-SY-AmanyNeural", "ar-SY-LaithNeural", "ar-TN-HediNeural", "ar-TN-ReemNeural", "ar-YE-MaryamNeural", "ar-YE-SalehNeural", "az-AZ-BabekNeural", "az-AZ-BanuNeural", "bg-BG-BorislavNeural", "bg-BG-KalinaNeural", "bn-BD-NabanitaNeural", "bn-BD-PradeepNeural", "bn-IN-BashkarNeural", "bn-IN-TanishaaNeural", "bs-BA-GoranNeural", "bs-BA-VesnaNeural", "ca-ES-EnricNeural", "ca-ES-JoanaNeural", "cs-CZ-AntoninNeural", "cs-CZ-VlastaNeural", "cy-GB-AledNeural", "cy-GB-NiaNeural", "da-DK-ChristelNeural", "da-DK-JeppeNeural", "de-AT-IngridNeural", "de-AT-JonasNeural", "de-CH-JanNeural", "de-CH-LeniNeural", "de-DE-AmalaNeural", "de-DE-ConradNeural", "de-DE-KatjaNeural", "de-DE-KillianNeural", "el-GR-AthinaNeural", "el-GR-NestorasNeural", "en-AU-NatashaNeural", "en-AU-WilliamNeural", "en-CA-ClaraNeural", "en-CA-LiamNeural", "en-GB-LibbyNeural", "en-GB-MaisieNeural", "en-GB-MiaNeural", "en-GB-RyanNeural", "en-GB-SoniaNeural", "en-GB-ThomasNeural", "en-HK-SamNeural", "en-HK-YanNeural", "en-IE-ConnorNeural", "en-IE-EmilyNeural", "en-IN-NeerjaNeural", "en-IN-PrabhatNeural", "en-KE-AsiliaNeural", "en-KE-ChilembaNeural", "en-NG-AbeoNeural", "en-NG-EzinneNeural", "en-NZ-MitchellNeural", "en-NZ-MollyNeural", "en-PH-JamesNeural", "en-PH-RosaNeural", "en-SG-LunaNeural", "en-SG-WayneNeural", "en-TZ-ElimuNeural", "en-TZ-ImaniNeural", "en-US-AnaNeural", "en-US-AriaNeural", "en-US-ChristopherNeural", "en-US-EricNeural", "en-US-GuyNeural", "en-US-JennyNeural", "en-US-MichelleNeural", "en-US-RogerNeural", "en-US-SteffanNeural", "en-ZA-LeahNeural", "en-ZA-LukeNeural", "es-AR-ElenaNeural", "es-AR-TomasNeural", "es-BO-MarceloNeural", "es-BO-SofiaNeural", "es-CL-CatalinaNeural", "es-CL-LorenzoNeural", "es-CO-GonzaloNeural", "es-CO-SalomeNeural", "es-CR-JuanNeural", "es-CR-MariaNeural", "es-CU-BelkysNeural", "es-CU-ManuelNeural", "es-DO-EmilioNeural", "es-DO-RamonaNeural", "es-EC-AndreaNeural", "es-EC-LuisNeural", "es-ES-AlvaroNeural", "es-ES-ElviraNeural", "es-GQ-JavierNeural", "es-GQ-TeresaNeural", "es-GT-AndresNeural", "es-GT-MartaNeural", "es-HN-CarlosNeural", "es-HN-KarlaNeural", "es-MX-DaliaNeural", "es-MX-JorgeNeural", "es-NI-FedericoNeural", "es-NI-YolandaNeural", "es-PA-MargaritaNeural", "es-PA-RobertoNeural", "es-PE-AlexNeural", "es-PE-CamilaNeural", "es-PR-KarinaNeural", "es-PR-VictorNeural", "es-PY-MarioNeural", "es-PY-TaniaNeural", "es-SV-LorenaNeural", "es-SV-RodrigoNeural", "es-US-AlonsoNeural", "es-US-PalomaNeural", "es-UY-MateoNeural", "es-UY-ValentinaNeural", "es-VE-PaolaNeural", "es-VE-SebastianNeural", "et-EE-AnuNeural", "et-EE-KertNeural", "fa-IR-DilaraNeural", "fa-IR-FaridNeural", "fi-FI-HarriNeural", "fi-FI-NooraNeural", "fil-PH-AngeloNeural", "fil-PH-BlessicaNeural", "fr-BE-CharlineNeural", "fr-BE-GerardNeural", "fr-CA-AntoineNeural", "fr-CA-JeanNeural", "fr-CA-SylvieNeural", "fr-CH-ArianeNeural", "fr-CH-FabriceNeural", "fr-FR-DeniseNeural", "fr-FR-EloiseNeural", "fr-FR-HenriNeural", "ga-IE-ColmNeural", "ga-IE-OrlaNeural", "gl-ES-RoiNeural", "gl-ES-SabelaNeural", "gu-IN-DhwaniNeural", "gu-IN-NiranjanNeural", "he-IL-AvriNeural", "he-IL-HilaNeural", "hi-IN-MadhurNeural", "hi-IN-SwaraNeural", "hr-HR-GabrijelaNeural", "hr-HR-SreckoNeural", "hu-HU-NoemiNeural", "hu-HU-TamasNeural", "id-ID-ArdiNeural", "id-ID-GadisNeural", "is-IS-GudrunNeural", "is-IS-GunnarNeural", "it-IT-DiegoNeural", "it-IT-ElsaNeural", "it-IT-IsabellaNeural", "ja-JP-KeitaNeural", "ja-JP-NanamiNeural", "jv-ID-DimasNeural", "jv-ID-SitiNeural", "ka-GE-EkaNeural", "ka-GE-GiorgiNeural", "kk-KZ-AigulNeural", "kk-KZ-DauletNeural", "km-KH-PisethNeural", "km-KH-SreymomNeural", "kn-IN-GaganNeural", "kn-IN-SapnaNeural", "ko-KR-InJoonNeural", "ko-KR-SunHiNeural", "lo-LA-ChanthavongNeural", "lo-LA-KeomanyNeural", "lt-LT-LeonasNeural", "lt-LT-OnaNeural", "lv-LV-EveritaNeural", "lv-LV-NilsNeural", "mk-MK-AleksandarNeural", "mk-MK-MarijaNeural", "ml-IN-MidhunNeural", "ml-IN-SobhanaNeural", "mn-MN-BataaNeural", "mn-MN-YesuiNeural", "mr-IN-AarohiNeural", "mr-IN-ManoharNeural", "ms-MY-OsmanNeural", "ms-MY-YasminNeural", "mt-MT-GraceNeural", "mt-MT-JosephNeural", "my-MM-NilarNeural", "my-MM-ThihaNeural", "nb-NO-FinnNeural", "nb-NO-PernilleNeural", "ne-NP-HemkalaNeural", "ne-NP-SagarNeural", "nl-BE-ArnaudNeural", "nl-BE-DenaNeural", "nl-NL-ColetteNeural", "nl-NL-FennaNeural", "nl-NL-MaartenNeural", "pl-PL-MarekNeural", "pl-PL-ZofiaNeural", "ps-AF-GulNawazNeural", "ps-AF-LatifaNeural", "pt-BR-AntonioNeural", "pt-BR-FranciscaNeural", "pt-PT-DuarteNeural", "pt-PT-RaquelNeural", "ro-RO-AlinaNeural", "ro-RO-EmilNeural", "ru-RU-DmitryNeural", "ru-RU-SvetlanaNeural", "si-LK-SameeraNeural", "si-LK-ThiliniNeural", "sk-SK-LukasNeural", "sk-SK-ViktoriaNeural", "sl-SI-PetraNeural", "sl-SI-RokNeural", "so-SO-MuuseNeural", "so-SO-UbaxNeural", "sq-AL-AnilaNeural", "sq-AL-IlirNeural", "sr-RS-NicholasNeural", "sr-RS-SophieNeural", "su-ID-JajangNeural", "su-ID-TutiNeural", "sv-SE-MattiasNeural", "sv-SE-SofieNeural", "sw-KE-RafikiNeural", "sw-KE-ZuriNeural", "sw-TZ-DaudiNeural", "sw-TZ-RehemaNeural", "ta-IN-PallaviNeural", "ta-IN-ValluvarNeural", "ta-LK-KumarNeural", "ta-LK-SaranyaNeural", "ta-MY-KaniNeural", "ta-MY-SuryaNeural", "ta-SG-AnbuNeural", "ta-SG-VenbaNeural", "te-IN-MohanNeural", "te-IN-ShrutiNeural", "th-TH-NiwatNeural", "th-TH-PremwadeeNeural", "tr-TR-AhmetNeural", "tr-TR-EmelNeural", "uk-UA-OstapNeural", "uk-UA-PolinaNeural", "ur-IN-GulNeural", "ur-IN-SalmanNeural", "ur-PK-AsadNeural", "ur-PK-UzmaNeural", "uz-UZ-MadinaNeural", "uz-UZ-SardorNeural", "vi-VN-HoaiMyNeural", "vi-VN-NamMinhNeural", "zh-CN-XiaoxiaoNeural", "zh-CN-XiaoxuanNeural", "zh-CN-XiaoyiNeural", "zh-CN-YunjianNeural", "zh-CN-YunxiNeural", "zh-CN-YunxiaNeural", "zh-CN-YunyangNeural", "zh-CN-liaoning-XiaobeiNeural", "zh-CN-shaanxi-XiaoniNeural", "zh-HK-HiuGaaiNeural", "zh-HK-HiuMaanNeural", "zh-HK-WanLungNeural", "zh-TW-HsiaoChenNeural", "zh-TW-HsiaoYuNeural", "zh-TW-YunJheNeural", "zu-ZA-ThandoNeural", "zu-ZA-ThembaNeural"]

const azureRegions = [
  { "DisplayName": "East US", "Name": "eastus" },
  { "DisplayName": "East US 2", "Name": "eastus2" },
  { "DisplayName": "South Central US", "Name": "southcentralus" },
  { "DisplayName": "West US 2", "Name": "westus2" },
  { "DisplayName": "West US 3", "Name": "westus3" },
  { "DisplayName": "Australia East", "Name": "australiaeast" },
  { "DisplayName": "Southeast Asia", "Name": "southeastasia" },
  { "DisplayName": "North Europe", "Name": "northeurope" },
  { "DisplayName": "Sweden Central", "Name": "swedencentral" },
  { "DisplayName": "UK South", "Name": "uksouth" },
  { "DisplayName": "West Europe", "Name": "westeurope" },
  { "DisplayName": "Central US", "Name": "centralus" },
  { "DisplayName": "South Africa North", "Name": "southafricanorth" },
  { "DisplayName": "Central India", "Name": "centralindia" },
  { "DisplayName": "East Asia", "Name": "eastasia" },
  { "DisplayName": "Japan East", "Name": "japaneast" },
  { "DisplayName": "Korea Central", "Name": "koreacentral" },
  { "DisplayName": "Canada Central", "Name": "canadacentral" },
  { "DisplayName": "France Central", "Name": "francecentral" },
  { "DisplayName": "Germany West Central", "Name": "germanywestcentral" },
  { "DisplayName": "Italy North", "Name": "italynorth" },
  { "DisplayName": "Norway East", "Name": "norwayeast" },
  { "DisplayName": "Poland Central", "Name": "polandcentral" },
  { "DisplayName": "Spain Central", "Name": "spaincentral" },
  { "DisplayName": "Switzerland North", "Name": "switzerlandnorth" },
  { "DisplayName": "Mexico Central", "Name": "mexicocentral" },
  { "DisplayName": "UAE North", "Name": "uaenorth" },
  { "DisplayName": "Brazil South", "Name": "brazilsouth" },
  { "DisplayName": "Israel Central", "Name": "israelcentral" },
  { "DisplayName": "Qatar Central", "Name": "qatarcentral" },
  { "DisplayName": "Central US (Stage)", "Name": "centralusstage" },
  { "DisplayName": "East US (Stage)", "Name": "eastusstage" },
  { "DisplayName": "East US 2 (Stage)", "Name": "eastus2stage" },
  { "DisplayName": "North Central US (Stage)", "Name": "northcentralusstage" },
  { "DisplayName": "South Central US (Stage)", "Name": "southcentralusstage" },
  { "DisplayName": "West US (Stage)", "Name": "westusstage" },
  { "DisplayName": "West US 2 (Stage)", "Name": "westus2stage" },
  { "DisplayName": "Asia", "Name": "asia" },
  { "DisplayName": "Asia Pacific", "Name": "asiapacific" },
  { "DisplayName": "Australia", "Name": "australia" },
  { "DisplayName": "Brazil", "Name": "brazil" },
  { "DisplayName": "Canada", "Name": "canada" },
  { "DisplayName": "Europe", "Name": "europe" },
  { "DisplayName": "France", "Name": "france" },
  { "DisplayName": "Germany", "Name": "germany" },
  { "DisplayName": "Global", "Name": "global" },
  { "DisplayName": "India", "Name": "india" },
  { "DisplayName": "Israel", "Name": "israel" },
  { "DisplayName": "Italy", "Name": "italy" },
  { "DisplayName": "Japan", "Name": "japan" },
  { "DisplayName": "Korea", "Name": "korea" },
  { "DisplayName": "New Zealand", "Name": "newzealand" },
  { "DisplayName": "Norway", "Name": "norway" },
  { "DisplayName": "Poland", "Name": "poland" },
  { "DisplayName": "Qatar", "Name": "qatar" },
  { "DisplayName": "Singapore", "Name": "singapore" },
  { "DisplayName": "South Africa", "Name": "southafrica" },
  { "DisplayName": "Sweden", "Name": "sweden" },
  { "DisplayName": "Switzerland", "Name": "switzerland" },
  { "DisplayName": "United Arab Emirates", "Name": "uae" },
  { "DisplayName": "United Kingdom", "Name": "uk" },
  { "DisplayName": "United States", "Name": "unitedstates" },
  { "DisplayName": "United States EUAP", "Name": "unitedstateseuap" },
  { "DisplayName": "East Asia (Stage)", "Name": "eastasiastage" },
  { "DisplayName": "Southeast Asia (Stage)", "Name": "southeastasiastage" },
  { "DisplayName": "Brazil US", "Name": "brazilus" },
  { "DisplayName": "East US STG", "Name": "eastusstg" },
  { "DisplayName": "North Central US", "Name": "northcentralus" },
  { "DisplayName": "West US", "Name": "westus" },
  { "DisplayName": "Japan West", "Name": "japanwest" },
  { "DisplayName": "Jio India West", "Name": "jioindiawest" },
  { "DisplayName": "Central US EUAP", "Name": "centraluseuap" },
  { "DisplayName": "East US 2 EUAP", "Name": "eastus2euap" },
  { "DisplayName": "West Central US", "Name": "westcentralus" },
  { "DisplayName": "South Africa West", "Name": "southafricawest" },
  { "DisplayName": "Australia Central", "Name": "australiacentral" },
  { "DisplayName": "Australia Central 2", "Name": "australiacentral2" },
  { "DisplayName": "Australia Southeast", "Name": "australiasoutheast" },
  { "DisplayName": "Jio India Central", "Name": "jioindiacentral" },
  { "DisplayName": "Korea South", "Name": "koreasouth" },
  { "DisplayName": "South India", "Name": "southindia" },
  { "DisplayName": "West India", "Name": "westindia" },
  { "DisplayName": "Canada East", "Name": "canadaeast" },
  { "DisplayName": "France South", "Name": "francesouth" },
  { "DisplayName": "Germany North", "Name": "germanynorth" },
  { "DisplayName": "Norway West", "Name": "norwaywest" },
  { "DisplayName": "Switzerland West", "Name": "switzerlandwest" },
  { "DisplayName": "UK West", "Name": "ukwest" },
  { "DisplayName": "UAE Central", "Name": "uaecentral" },
  { "DisplayName": "Brazil Southeast", "Name": "brazilsoutheast" }
]

</script>

<style>
.form-label {
    font-weight: bold;
    margin-bottom: 8px;
}
</style>